# Dockerfile
FROM python:3.9-bullseye

MAINTAINER Kevin Nguyen <kevin.nguyen.eng@gmail.com>

RUN apt-get update && apt-get -y install libpq-dev mariadb-client libmariadb-dev libev-dev libevdev2

RUN git clone https://github.com/ronny-rentner/UltraDict.git
WORKDIR /UltraDict
RUN pip install --upgrade pip && \
    pip install Cython && \
    python setup.py build && \
    python setup.py install

COPY ./  /opt/dsiprouter/
WORKDIR /opt/dsiprouter
RUN pip install -r ./gui/requirements.txt
ENV DBSERVER ''
ENV DBPORT '3306'
ENV DBUSER ''
ENV DBPASS ''
ENV DBNAME ''

EXPOSE 5000:5000

CMD ["python", "./gui/dsiprouter.py", "runserver"]
